# controller:
#   resources: {}
#    requests:
#      cpu: 1
#      memory: 1Gi
#    limits:
#      cpu: 1
#      memory: 1Gi

serviceAcccount:
  create: false
  name: ${serviceaccount}

settings:
  clusterName: ${clustername}
  interruptionQueue: ${sqs}