serviceAccount:
    create: true
    name: fluent-bit
    annotations:
        eks.amazonaws.com/role-arn: ${fluent-bit-role}
        meta.helm.sh/release-namespace: logging
        app.kubernetes.io/managed-by: Helm

config:
  inputs: |
    [INPUT]
        Name                tail     
        Tag                 app.*
        Path                /var/log/containers/*.log
        Exclude_Path        /var/log/containers/*_kube-system_*.log,/var/log/containers/*_kubecost_*.log,/var/log/containers/*_k8tz-*.log,/var/log/containers/*_logging_*.log,/var/log/containers/*_keycloak_*.log
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
    
    [INPUT]
        Name                tail
        Tag                 ingress.*
        Path                /var/log/containers/ingress-nginx-*.log,/var/log/containers/aws-load-balancer-*.log
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        
  filters: |
    [FILTER]
        Name                modify
        Match               app.*
        Remove              _p
        Remove              stream
        Remove              logtag
        Rename              message log

    [FILTER]
        Name                kubernetes
        Match               app.*
        Kube_Tag_Prefix     app.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off
    
    [FILTER]
        Name                nest
        Match               app.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes.   

    [FILTER]
        Name                modify
        Match               app.*
        Remove              kubernetes.container_hash
        Remove              kubernetes.container_name
        Remove              kubernetes.docker_id
        Remove              kubernetes.pod_id
        Remove              kubernetes.pod_name  

    [FILTER]
        Name                nest
        Match               app.*
        Operation           nest
        Wildcard            kubernetes_labels.*
        Nest_under          kubernetes.labels
        Remove_prefix       kubernetes_labels.   

    [FILTER]
        Name                nest
        Match               app.*
        Operation           nest
        Wildcard            kubernetes.*
        Nested_under        kubernetes
        Remove_prefix       kubernetes.        
        
  outputs: |
    [OUTPUT]
        Name           es
        Match          app.*
        Host           ${es_host}
        Port           443
        Suppress_Type_Name On
        Retry_Limit    False
        tls            On
        tls.verify     Off
        HTTP_User      ${es_user}
        HTTP_Passwd    ${es_password}
        Index          fluentbit
    
    [OUTPUT]
        Name           es
        Match          ingress.*
        Host           ${es_host}
        Port           443
        Suppress_Type_Name On
        Retry_Limit    False
        tls            On
        tls.verify     Off
        HTTP_User      ${es_user}
        HTTP_Passwd    ${es_password}
        Index          ingress

