serviceAccount:
    create: true
    name: fluent-bit
    annotations:
        eks.amazonaws.com/role-arn: ${fluent-bit-role}
        meta.helm.sh/release-namespace: logging
        app.kubernetes.io/managed-by: Helm
serviceMonitor:
    enabled: true

config:
  inputs: |
    [INPUT]
        Name                tail     
        Tag                 fluentbit.*
        Path                /var/log/containers/*.log
        Exclude_Path        /var/log/containers/*_kube-system_*,/var/log/containers/*_kubecost_*,/var/log/containers/*_k8tz-*,/var/log/containers/*_logging_*,/var/log/containers/*_keycloak_*,/var/log/containers/*_argocd_*,/var/log/containers/*_elastic_system_*
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
    
    [INPUT]
        Name                tail
        Tag                 ingress.*
        Path                /var/log/containers/ingress-nginx-*,/var/log/containers/aws-load-balancer-*
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
    
    [INPUT]
        Name                tail
        Tag                 cicd.*
        Path                /var/log/containers/*_jenkins_jenkins-*,/var/log/containers/*-argocd-server-*
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On

    [INPUT]
        Name                tail
        Tag                 default.*
        Path                /var/log/containers/*_default_*
        Parser              cri
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        
  filters: |
    [FILTER]
        Name                modify
        Match               *
        Remove              _p
        Remove              logtag
        Rename              message log

    [FILTER]
        Name                kubernetes
        Match               fluentbit.*
        Kube_Tag_Prefix     fluentbit.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off 
    
    [FILTER]
        Name                nest
        Match               fluentbit.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes.
        
    [FILTER]
        Name                modify
        Match               fluentbit.*
        REMOVE              kubernetes.pod_name
        REMOVE              kubernetes.pod_id
        REMOVE              kubernetes.host
        REMOVE              kubernetes.container_name
        REMOVE              kubernetes.docker_id
        REMOVE              kubernetes.container_hash
    
    # # stdout 로그는 access 태그, nginx 이미지만 해당 ㅠㅠ
    # [FILTER]
    #     Name                rewrite_tag
    #     Match               default.*
    #     Rule                $stream stdout default.access.* false
    
    # # stderr 로그는 error 태그
    # [FILTER]
    #     Name                rewrite_tag
    #     Match               default.*
    #     Rule                $stream stderr default.error.* false

    [FILTER]
        Name                kubernetes
        Match               default.*
        Kube_Tag_Prefix     default.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off
    
    [FILTER]
        Name                nest
        Match               default.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes.

    [FILTER]
        Name                modify
        Match               default.*
        Remove              kubernetes.namespace_name
        Remove              kubernetes.pod_id
        Remove              kubernetes.docker_id
        Remove              kubernetes.container_hash
        Remove              kubernetes.container_image
    
    [FILTER]
        Name                nest
        Match               default.*
        Operation           lift
        Nested_under        kubernetes.labels
        Add_prefix          kubernetes.labels_
    
    [FILTER]
        Name                nest
        Match               default.*
        Operation           nest
        Wildcard            kubernetes.*
        Nest_under          kubernetes
        Remove_prefix       kubernetes.

  outputs: |
    [OUTPUT]
        Name                es
        Match               fluentbit.*
        Host                ${es_host}
        Port                443
        Suppress_Type_Name  On
        Retry_Limit         False
        tls                 On
        tls.verify          Off
        HTTP_User           ${es_user}
        HTTP_Passwd         ${es_password}
        Index               fluentbit
        Trace_Error         On
    
    [OUTPUT]
        Name                es
        Match               ingress.*
        Host                ${es_host}
        Port                443
        Suppress_Type_Name  On
        Retry_Limit         False
        tls                 On
        tls.verify          Off
        HTTP_User           ${es_user}
        HTTP_Passwd         ${es_password}
        Index               ingress
        Trace_Error         On

    [OUTPUT]
        Name                es
        Match               cicd.*
        Host                ${es_host}
        Port                443
        Suppress_Type_Name  On
        Retry_Limit         False
        tls                 On
        tls.verify          Off
        HTTP_User           ${es_user}
        HTTP_Passwd         ${es_password}
        Index               cicd
        Trace_Error         On
    
    [OUTPUT]
        Name                es
        Match               default.*
        Host                ${es_host}
        Port                443
        Suppress_Type_Name  On
        Retry_Limit         False
        tls                 On
        tls.verify          Off
        HTTP_User           ${es_user}
        HTTP_Passwd         ${es_password}
        Index               default
        Trace_Error         On

    # [OUTPUT]
    #     Name                es
    #     Match               default.error.*
    #     Host                ${es_host}
    #     Port                443
    #     Suppress_Type_Name  On
    #     Retry_Limit         False
    #     tls                 On
    #     tls.verify          Off
    #     HTTP_User           ${es_user}
    #     HTTP_Passwd         ${es_password}
    #     Index               default.error
    #     Trace_Error         On
