prometheus:
  type: NodePort
  ingress:
    enabled: true
    hosts: 
      - prom.gguduck.com
    # paths:
    #   - /
    annotations:
        meta.helm.sh/release-namespace: monitoring
        app.kubernetes.io/managed-by: Helm
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: prom.gguduck.com
    ingressClassName: ${ingressclass}
    servicePort: 80

grafana:
  ingress:
    enabled: true
    annotations:
        meta.helm.sh/release-namespace: monitoring
        app.kubernetes.io/managed-by: Helm
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: graf.gguduck.com
    hosts: 
      - graf.gguduck.com
    ingressClassName: ${ingressclass}
    # path: 
    #   - /

