global:
  grafana:
    enabled: false
    proxy: false

networkCosts:
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs
    tag: v0.17.6

ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.annotations.nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  hosts: 
  - ${hostname}
  pathType: Prefix

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  ipv6:
    enabled: false

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model

forecasting:
  fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.18

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

reporting:
  productAnalytics: false
