alertmanager:
  alertmanagerSpec:
    replicas: 2       # 1인 경우에는 alertmanager의 cluster stauts가 disable로 사용불가, replica를 추가해줘야 정상적으로 등록가능
  enabled: true
  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations:
        ingress.annotations.nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    hosts:
      - ${alert_url}
    paths:
      - /

prometheus:
  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations:
        ingress.annotations.nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    hosts:
      - ${prom_url}
    paths:
      - /
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  adminPassword: ${grafana_admin_password}
  defaultDashboardsTimezone: Asia/Seoul   # default 타임존 설정
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
        ingress.annotations.nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    hosts: 
      - ${grafana_url}
    paths: 
      - /*

defaultRules:       # 기본으로 사용할 rule 설정
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: false
    general: false
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: false
    k8sContainerMemoryRss: false
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sContainerMemoryWorkingSetBytes: false
    k8sPodOwner: false
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: true
    kubeProxy: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: false
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: true
    prometheusOperator: true
 